
# // Create Partners
# POST http://localhost:5000/users
# Content-Type: application/json

# {
#     "nama" : "Hanun Shaka",
#     "email": "hanunshaka02@gmail.com",
#     "no_telp": "085156961624",
# 	"password": "Aainoene83",
#     "confPassword": "Aainoene83"
# }

# ###
# // Get All Partners
# GET http://localhost:5000/partners

# ###
# // Get Single Partners
# GET http://localhost:5000/partners/1

# ###
# // Update Partner
# PATCH http://localhost:5000/partners/1
# Content-Type: application/json

# {
#     "nama" : "Hanun Shaka Update",
#     "email": "hanunshaka02@gmail.com",
#     "no_telp": "085156961624",
# 	"password": "",
#     "confPassword": "",
#     "alamat": "Jalan Tomat Surabaya"
# }

# ###
# // Delete Partner
# DELETE  http://localhost:5000/partners/1





###
// Create Users
POST http://localhost:3000/users
Content-Type: application/json

{
    "nama" : "Katarina Inezita",
    "email": "inezitakatarina16@gmail.com",
    "no_telp": "085156961625",
	"password": "Aai94i",
    "confirm_password": "Aai94i"
}

###
// Create User Mitra
POST http://localhost:5000/usermitra
Content-Type: application/json

{
    "nama" : "Naufalqi",
    "email": "naufalqinaufalqi@gmail.com",
    "no_telp": "085156961625",
	"password": "Naufalqii02",
    "confPassword": "Naufalqii02"
}

# {
#     "nama" : "Hanun Shaka Update",
#     "email": "hanunshaka02@gmail.com",
#     "no_telp": "085156961624",
# 	"password": "Aai94i94oene83",
#     "confPassword": "Aai94i94oene83",
#     "role": "admin"
# }

###
// Get All Users
GET http://localhost:5000/users

###
// Get Single Users
GET http://localhost:5000/users/2

###
// Update Users
PATCH http://localhost:5000/users/1
Content-Type: application/json

{
    "nama" : "Katarina Inezita Update",
    "email": "inezitakatarina16@gmail.com",
    "no_telp": "085156961625",
	"password": "",
    "confPassword": ""
}

###
// Delete User
DELETE  http://localhost:5000/users/1



###
// Login Users
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "inezitakatarina16@gmail.com",
    "password": "Aai94i"
}

###
// Login Partners
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "hanunshaka02@gmail.com",
    "password": "Aai94i94oene83"
}

// Tampilin siapa yg lagi login
###
GET http://localhost:3000/users/me

// Logout Users
###
DELETE http://localhost:5000/logout


// Get All Activities
###
GET http://localhost:3000/activities


// Create Activity
###
POST http://localhost:3000/activities/66b1b000-7f13-488f-bbbb-728a21685c1d
Content-Type: application/json

# {
#     "nama": "Strolling at Kota Lama Semarang",
#     "deskripsi": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
#     "harga": "1000",
#     "fitur": "  Mengenal sudut Kota Lama Semarang",
#     "bintang": "4",
#     "lokasi": "Semarang",
#     "kontak_pengelola": "089264829202"

# }

# {
#     "nama": "Alun Alun Surabaya",
#     "deskripsi": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
#     "harga": "2000",
#     "fitur": "  Mengenal Surabaya",
#     "bintang": "3",
#     "lokasi": "Surabaya",
#     "nama_tourguide": "Ojan",
#     "kontak_tourguide": "087352839473",
#     "userId": 3
# }

{
    "nama": "Berkebun di Kebun Raya Purwodadi",
    "deskripsi": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    "harga": "5000",
    "fitur": "  Mengenal Kebun Raya Purwodadi",
    "bintang": "5",
    "lokasi": "Purwodadi",
    "nama_tourguide": "Ojan",
    "kontak_tourguide": "087352839473"
}

# {
#     "nama": "Rawon Setan",
#     "deskripsi": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
#     "harga": "10000",
#     "fitur": "  Mengenal Kuliner Rawon",
#     "bintang": "5",
#     "lokasi": "Sidoarjo",
#     "nama_tourguide": "Sujono",
#     "kontak_tourguide": "086537292736"

# }

# {
#     "nama": "Alun Alun Surabaya",
#     "deskripsi": "Lorem ipsum dolor",
#     "harga": "50000",
#     "fitur": "Mengenal Surabaya",
#     "bintang": "5",
#     "lokasi": "Surabaya",
#     "nama_tourguide": "Siska Uri",
#     "kontak_tourguide": "087352839473"

# }

// Get Single Activity
###
GET http://localhost:5000/activities/2


// Update Activity
###
PATCH http://localhost:5000/activities/3
Content-Type: application/json

{
    "nama": "Snorkeling Surabaya",
    "deskripsi": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "harga": "5000",
    "fitur": "  Mengenal Kuliner Kupang",
    "bintang": "3",
    "lokasi": "Sidoarjo",
    "nama_tourguide" : "Sujono",
    "kontak_tourguide": "086537292736"

}


// Delete Activity
###
DELETE  http://localhost:5000/activities/3



// Get All Transaction
###
GET http://localhost:5000/transactions/1


// Get pending transaction
###
GET http://localhost:5000/pending_transactions/2


// Create Transaction
###
POST http://localhost:5000/transactions/1
Content-Type: application/json

{
    "metode_pembayaran": "transfer",
    "harga_total": "50000",
    "status": "menunggu verifikasi",
    "sesisId": 1,
    "slot_dibeli": 2
}

// Update Transaction
###
PATCH http://localhost:5000/transactions/1
Content-Type: application/json

{
    "metode_pembayaran": "transfer",
    "harga_total": "50000",
    "status": "batal"
}

// Delete Transaction
###
DELETE http://localhost:5000/transactions/1

// Create Sesi
###
POST http://localhost:5000/sesis/1
Content-Type: application/json

{
    "nama": "sesi 1",
    "tanggal": "2023-11-2",
    "mulai": "15:00",
    "selesai": "17:00",
    "slot_maks": "10",
    "slot_booked": "5"
}


// Get Sesi By Activity Id
###
GET http://localhost:5000/sesis/1

// Update
###
PUT http://localhost:5000/sesis/2
Content-Type: application/json

{
    "nama": "sesi 3",
    "tanggal": "13-11-2023",
    "mulai": "07:00",
    "selesai": "17:00",
    "slot_maks": "10",
    "slot_booked": "5"
}

###
DELETE http://localhost:5000/sesis/2


// Create Images
###
POST http://localhost:5000/images/1
Content-Type: application/json

# {
#     "nama": "gambar 1",
#     "url": "https://i.pinimg.com/originals/8e/6e/f4/8e6ef47115093685498e84a4db41f736.jpg"
# }

{
    "nama": "gambar 2",
    "url": "https://i.pinimg.com/originals/8e/6e/f4/8e6ef47115093685498e84a4db41f736.jpg"
}

// Get Images By Activity Id
###
GET http://localhost:5000/images/1

// Update Image By Id
###
PUT http://localhost:5000/images/1
Content-Type: application/json

{
    "nama": "gambar 1 update",
    "url":"https://i.pinimg.com/originals/8e/6e/f4/8e6ef47115093685498e84a4db41f736.jpg"
}


###
DELETE http://localhost:5000/images/2


// Create Cart
###
POST http://localhost:5000/carts/1
Content-Type: application/json

// Get Cart
###
GET http://localhost:5000/carts

// Delete Cart
###
DELETE http://localhost:5000/carts/1

// Create Detail
###
POST http://localhost:5000/details/1
Content-Type: application/json

{
    "jumlah": "3"
}

// Get Detail
###
GET http://localhost:5000/details/1

// Update Detail
###
PUT http://localhost:5000/details/1
Content-Type: application/json

{
    "jumlah": "1"
}

// Delete Detail
###
DELETE http://localhost:5000/details/1